name = "hono-blog"
main = "src/index.ts"
compatibility_date = "2023-12-01"

[vars]
MICROCMS_SERVICE_DOMAIN = "demo"
MICROCMS_API_KEY = "demo-key"

[env.production.vars]
MICROCMS_SERVICE_DOMAIN = ""
MICROCMS_API_KEY = ""